[package]
name = "my_token"
version = "0.0.1"

[addresses]
StarcoinFramework = "0x1"
MY_TOKEN = "0xABCDE"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin.git", subdir="vm/stdlib", rev="3e895169a8f8dd883277050bb90645c52a370cee"}
